/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EntryPageId {
  retcode: number;
  message: string;
  data: {
    page: {
      id: string;
      name: string;
      desc: string;
      icon_url: string;
      header_img_url: string;
      /**
       * @minItems 1
       */
      modules: [
        {
          name: string;
          is_poped: boolean;
          /**
           * @minItems 1
           */
          components?: [
            {
              component_id: string;
              layout: string;
              data: string;
              style: string;
              [k: string]: unknown;
            },
            ...{
              component_id: string;
              layout: string;
              data: string;
              style: string;
              [k: string]: unknown;
            }[],
          ];
          id: string;
          is_customize_name: boolean;
          is_abstract: boolean;
          is_show_switch: boolean;
          switch: boolean;
          desc: string;
          repeated: boolean;
          is_submodule: boolean;
          origin_module_id: string;
          without_border: boolean;
          can_delete: boolean;
          is_hidden: boolean;
          [k: string]: unknown;
        },
        ...{
          name: string;
          is_poped: boolean;
          /**
           * @minItems 1
           */
          components?: [
            {
              component_id: string;
              layout: string;
              data: string;
              style: string;
              [k: string]: unknown;
            },
            ...{
              component_id: string;
              layout: string;
              data: string;
              style: string;
              [k: string]: unknown;
            }[],
          ];
          id: string;
          is_customize_name: boolean;
          is_abstract: boolean;
          is_show_switch: boolean;
          switch: boolean;
          desc: string;
          repeated: boolean;
          is_submodule: boolean;
          origin_module_id: string;
          without_border: boolean;
          can_delete: boolean;
          is_hidden: boolean;
          [k: string]: unknown;
        }[],
      ];
      filter_values: {
        agent_faction: {
          values: {
            [k: string]: unknown;
          }[];
          /**
           * @minItems 1
           */
          value_types: [
            {
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            },
            ...{
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            }[],
          ];
          key: {
            key: string;
            text: string;
            values: {
              [k: string]: unknown;
            }[];
            mi18n_key: string;
            is_multi_select: boolean;
            id: string;
            is_hidden: boolean;
            updated_at: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        agent_rarity: {
          values: {
            [k: string]: unknown;
          }[];
          /**
           * @minItems 1
           */
          value_types: [
            {
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            },
            ...{
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            }[],
          ];
          key: {
            key: string;
            text: string;
            values: {
              [k: string]: unknown;
            }[];
            mi18n_key: string;
            is_multi_select: boolean;
            id: string;
            is_hidden: boolean;
            updated_at: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        agent_specialties: {
          values: {
            [k: string]: unknown;
          }[];
          /**
           * @minItems 1
           */
          value_types: [
            {
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            },
            ...{
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            }[],
          ];
          key: {
            key: string;
            text: string;
            values: {
              [k: string]: unknown;
            }[];
            mi18n_key: string;
            is_multi_select: boolean;
            id: string;
            is_hidden: boolean;
            updated_at: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        agent_stats: {
          values: {
            [k: string]: unknown;
          }[];
          /**
           * @minItems 1
           */
          value_types: [
            {
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            },
            ...{
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            }[],
          ];
          key: {
            key: string;
            text: string;
            values: {
              [k: string]: unknown;
            }[];
            mi18n_key: string;
            is_multi_select: boolean;
            id: string;
            is_hidden: boolean;
            updated_at: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        agent_attack_type: {
          values: {
            [k: string]: unknown;
          }[];
          /**
           * @minItems 1
           */
          value_types: [
            {
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            },
            ...{
              id: string;
              value: string;
              mi18n_key: string;
              icon: string;
              enum_string: string;
              [k: string]: unknown;
            }[],
          ];
          key: {
            key: string;
            text: string;
            values: {
              [k: string]: unknown;
            }[];
            mi18n_key: string;
            is_multi_select: boolean;
            id: string;
            is_hidden: boolean;
            updated_at: string;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      menu_id: string;
      menu_name: string;
      version: string;
      langs: {
        [k: string]: unknown;
      }[];
      template_layout: {
        [k: string]: unknown;
      };
      edit_lock_status: string;
      correct_lock_status: string;
      menus: {
        [k: string]: unknown;
      }[];
      template_id: string;
      ext: {
        fe_ext: string;
        post_ext: {
          post_id: string;
          post_user_name: string;
          post_time: string;
          post_avatar_url: string;
          url: string;
          [k: string]: unknown;
        };
        server_ext: string;
        personalized_color: string;
        scrolling_text: string;
        [k: string]: unknown;
      };
      alias_name: string;
      lang: string;
      beta: boolean;
      page_type: string;
      menu_style: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
